Реализация алгоритма диагонализации матрицы из книги автора Тыртышкин "Матричный анализ и линейная алгебра"

In [8]:
import numpy as np

def f(A, eps):
  def h(A): #сумма внедиагональных элементов
    sum = 0.0
    for i in range(A.shape[0]):
      for j in range(i):
        sum = sum + 2*A[i][j]*A[i][j]
    return sum
  def matrix_rotate(A, i, j): #возвращает матрицу поворота (i < j) зануляющую a_ij и a_ji
    E = np.eye(A.shape[0])
    fi = 0.0
    if(np.isclose(A[i][j], 0.0)):
      fi = 0.0
    else:
      fi = (np.pi/2.0 - np.arctan((A[i][i] - A[j][j])/(2.0*A[i][j])))/2.0
    E[i][i] = np.cos(fi)
    E[j][j] = np.cos(fi)
    E[i][j] = (-1.0)*np.sin(fi)
    E[j][i] = np.sin(fi)
    return E

  def search(A):#поиск наибольшего внедиагонального элемента
    max = (-1, 0)
    for j in range(A.shape[0]):
      for i in range(j):
        if(max[0] == -1):
          max = (i, j)
        else:
          if(np.abs(A[i][j]) > np.abs(A[max[0]][max[1]])): max = (i, j)
    return max
  h0 = h(A)
  k = round(np.log(eps/h(A))/np.log(1 - 2.0/(A.shape[0]*A.shape[0] - A.shape[0]))) #кол-во шагов
  for i in range(k):
    max_abs = search(A)
    R = matrix_rotate(A, max_abs[0], max_abs[1])
    A = R.transpose() @ A @ R
  #print((np.power(1.0 - 2.0/(A.shape[0]*A.shape[0] - A.shape[0]), k)*h0 - h(A) >= 0)) проверка оценки
  return A

def create_random_symmetrical_matrix(n):
  A = np.eye(n)
  for i in range(n):
    for j in range(i + 1):
      value = np.random.random()*1000.0
      A[i][j] = value
      A[j][i] = value
  return A

A = create_random_symmetrical_matrix(3)
print(f(A, 0.0000001))


[[-4.89457791e+01 -4.44505614e-14  2.49433060e-09]
 [-2.91249066e-14  1.45344930e+03  1.38608557e-13]
 [ 2.49434535e-09  1.24413774e-13 -4.13146809e+02]]
